### ISSUE TITLE
http://igv.org/app - No error message when file fails to load due to CORS policy

### ISSUE THREAD

**Issue by kubu4** [igvteam/igv-webapp#104]
I loaded a genome FastA and corresponding index file from a URL. Everything appeared fine (i.e. the chromosomes all showed up in the drop down list for this genome. However, the default track displayed "Error loading track data". 

After poking around the issues in this repo, I was able to figure out to look at the browser inspector thingy to see what was going on in my web browser. This is where I saw the CORS policy failure:

![20190731_005](https://user-images.githubusercontent.com/4514104/62233060-96dea100-b37c-11e9-8b2f-7c62854f8631.png)

Without an error message to alert the user and describe the problem makes it frustrating to use http://igv.org/app. 

Aa an aside, I've briefly read about the CORS policy stuff and it's way beyond anything our lab can understand/implement. We have a NAS that we use to host our data files for public/remote access. The server configuration needed to implement CORS (if it's even an option), is well beyond any of our understanding.

**Comment by jrobinso** [comment]
Apologies for the lack or an error message.   I'll look into that.   The problem is this is a low level error that our application (igv.js) does not even see directly.    Still there might be a way for the app to detect it.

WRT CORS,  this is not a rule we made up obviously.   If you want to serve data for any javascript program not running on the same host as the data you have to enable CORS.    If you install igv-web as a local application,  on the same host as the data resides,  you won't have to deal with this.     Details are documented here:  https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements

I also note your data is served by http, not https,  for that to work be sure you access the application trying to read it by http.   Otherwise the browser will block your request.   So for example http://igv.org/app,  or http://yourserver/app,   not https:

**Comment by kubu4** [comment]
> Apologies for the lack or an error message. 

No problem! Just wanted to pass along the info, in case you weren't aware of it.

Thanks for the heads up on the http vs https. I was using http://igv.org/app, so I fed it my data via http. We can/do use https, usually.

**Comment by jrobinso** [comment]
@kubu4 I thought you had another issue open about customizing the web app with your own genomes and tracks, but I can't find it.   I just went through the process myself with no issues, if that is still a problem open another git issue or point me to the existing one and we can discuss.  IIRC you also discovered that your genome takes a long time to load with no spinner or other feedback.    I was able to reproduce that and will work on a fix for the next igv.js release.   This occurs with large annotation files that are not indexed.

**Comment by kubu4** [comment]
>  I thought you had another issue open about customizing the web app with your own genomes and tracks, but I can't find it.

That issue is here: 
https://github.com/igvteam/igv-webapp/issues/103

I closed the issue because it _does_ work - it just took a very long time and there was no indicator that anything was actually happening.

---

>  IIRC you also discovered that your genome takes a long time to load with no spinner or other feedback

Yep, that's here: https://github.com/igvteam/igv-webapp/issues/103#issuecomment-516932616

---

> will work on a fix for the next igv.js release

Cool, thanks!

**Comment by jrobinso** [comment]
This should be resolved, if not re-open.
