### ISSUE TITLE
Cannot load gnomad vcf into igv web app

### ISSUE THREAD

**Issue by SpacemanSpiff7** [igvteam/igv-webapp#109]
Trying to add data from this link:
https://storage.googleapis.com/gnomad-public/release/2.1.1/vcf/genomes/gnomad.genomes.r2.1.1.sites.22.vcf.bgz

Error message:
Track File Error
Invalid Files
gnomad.genomes.r2.1.1.sites.22.vcf.bgz

It looks like it wants a .gz file. Is there an extension that supports .bgz or is there a step I'm skipping? 
Thank you!

**Comment by helgathorv** [comment]
Since this was about at the web app, I transferred this issue to the igvteam/igv-webapp repo

**Comment by jrobinso** [comment]
@SpacemanSpiff7 apologies for the long delay.  These files raised a few issues due to their size.  igv.js now supports them.  Unfortunately you can't load them directly from the gnomad website because they have enable permissions to allow javascript programs, such as the igv web app, to load them.  Specifically "CORS" is not enabled.
