### ISSUE TITLE
GWAS manhattan plots

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [igvteam/igv-webapp#135]
Does igv-webapp support GWAS manhattan plot or is this feature only available for igv.js (I saw this track recently been added to igv.js!)

Thanks!

**Comment by jrobinso** [comment]
igv.js supports them, and you can load them during the configuration, but they are not yet supported through the "Tracks" menu.   We will have that updated within a few days.

**Comment by Parul-Kudtarkar** [comment]
Thank you @jrobinso. Keep us posted!

**Comment by jrobinso** [comment]
OK this is working now.  Here's an example  https://tinyurl.com/ycu9mdx7

To load a gwas track from the "Tracks" menu the extension must be ".gwas" or ".gwas.gz" if its gzipped, and the file must conform to the "gwas" description here: https://github.com/igvteam/igv.js/wiki/GWAS.   Let me know if you have problems.

**Comment by Parul-Kudtarkar** [comment]
wow! This is great. I will try. TYVM!

**Comment by Parul-Kudtarkar** [comment]
@jrobinso I have GWAS files that are ~150 MB compressed! I am not able to load these files; is there a possible solution to this. Thanks!

**Comment by jrobinso** [comment]
@Parul-Kudtarkar The only possible solution would be to index these files with tabix, then use the index and set a visibility window so that not too much of the file is loaded at once.   You would only see features when zoomed into that window, and obviously you would not see a whole-genome gwas view.  I can't give you detailed instructions on tabix but it has good documentation,  basically you will have to sort the GWAS by chromosome and position,  then "bgzip" it,  the index with tabix using the -S,  -b, and -e options.    The set indexURL in the track config to the ".tbi" index file, and set visibilityWindow.  You would have to experiment to see how large a visibilityWindow you could get away with,  for a whole-chromosome window set the value to -1.

**Comment by Parul-Kudtarkar** [comment]
@jrobinso thank you very much! That works and I can visualize the dataset at whole-chromosome range/window

**Comment by Parul-Kudtarkar** [comment]
@jrobinso any metrics on max size of gwas data that can be visualized at whole genome window?

**Comment by jrobinso** [comment]
I don't know precisely.   I have an 11mb test file and it works but it takes a few seconds to load.  The manhattan plot is just inherently hard to produce as each data point in the file is painted.   This type of plot was invented when files were a few kb.   A more efficient form for the same information is perhaps a "wig" or bigwig file.  You could script something to extract the maximum gwas score over genomic intervals to create a wig type file.
