### ISSUE TITLE
Local file / Server file?

### ISSUE THREAD

**Issue by VincentGardeux** [igvteam/igv-webapp#138]
Hello,

I installed this IGV web app on a lab's server, and it works like a charm. Thanks for the hard work.

An issue we are currently facing is that when we want to share datasets, tracks are missing. Probably because they were imported from "Local Files"?

I was wondering if there would be an easy solution to add a "Server file" option in the "Tracks" and "SessIon" dropdown menus. So we can see the files on the server hosting the web app.

Thanks in advance

**Comment by jrobinso** [comment]
Web browsers cannot capture and store information about local files, it would be a massive security hole if that were allowed.  "Server" is a vague term,  technically there are only URLs and local files.    So to share your files must be reachable by URL.   You can server them from the default "http-server" that is serving the webpage itself, or another webserver.  Below are instructions  using "http-server"  as an example.

First I recommend copying the "dist" folder after building, and running from the copy, so that any edits don't get overwritten the next time you build.    So for this example I will copy "dist" to a new folder "app".   I'm keeping "app" in the project folder, but you can copy it anywhere if you install http-server globally (```npm install --global http-server```).

To serve files they need to be in a folder under the root ("app" in this case).   Since they are probably not, we can use a symbolic link.   In my test case the files are located at ```/Users/jrobinso/testdata```.   So from within the "app" directory

```
ln -s /Users/jrobinso/testdata/ data
```
Within the "testdata" folder I have a "bam" subfolder,  I will create a json file to add these files to the Tracks menu and call it "my-tracks.json".   The file is stored under app/resources/tracks and looks like this

```
{
  "label": "My Tracks",
  "description": "",
  "tracks": [
    {
      "name": "BRAF bam",
      "type": "alignment",
      "format": "bam",
      "url": "data/bam/BRAF_C.bam",
      "indexURL": "data/bam/BRAF_C.bam.bai"
    },
    {
      "name": "GSTT1 bam",
      "type": "alignment",
      "format": "bam",
      "url": "data/bam/gstt1_sample.bam",
      "indexURL": "data/bam/gstt1_sample.bam.bai"
    }
  ]
}
```

 Note the url and indexURL are relative URLs (relative to the page html), I could also have used absolute urls

```
      "url": "http://127.0.0.1:8080/data/bam/BRAF_C.bam",
      "indexURL": "http://127.0.0.1:8080/data/bam/BRAF_C.bam.bai"
```

To add these items to the Tracks menu for genome hg19 I modify the "trackRegistry.json" file under app/resources/tracks as follows, adding my entry for "my-tracks.json" at the end

```
{
  "hg19": [
    "resources/tracks/hg19_annotations.json",
    "resources/tracks/hg19_variants.json",
    "resources/tracks/hg19_encode.json",
    "resources/tracks/hg19_platinum_genomes.json",
    "resources/tracks/hg19_tutorials.json",
    "resources/tracks/my-tracks.json"
  ],
...
```

I start my server on the "app" folder as follows, ran from the project root folder

```
http-server app
```

My new tracks are now in the menu (see screenshot),  and are sharable since they were loaded from urls 

<img width="254" alt="Screen Shot 2020-04-29 at 9 58 00 AM" src="https://user-images.githubusercontent.com/933148/80625210-bc7b0280-8a01-11ea-9758-7596ce4d0434.png">
