### ISSUE TITLE
How to link custom igv.js library to igv-webapp

### ISSUE THREAD

**Issue by martina-g** [igvteam/igv-webapp#151]
Hi,
I edited the lib `igv.js` so that now it can process files with a custom extension (`.cstex` hereafter).
In particular, I've changed the following files:

- js/bam/
             - bamSource.js
             - bamUtils.js

added a custom reader:

- js/cstex/
             - cstexReader.js

and finally tested the outcome in

-  dev/
          - cstex.html

The next step is to use the customized `igv.js` library in `igv-webapp/.`
I have no previous experience in how node.js works, but as far as I've understood,

- the folder` node-modules` is created when installing the project (`npm install`). It contains libraries and personal modules needed by` igv-webapp` (such as` igvteam/igv-widgets`).
* the folder `dist/ `instead is created when building the project (`npm build`). It contains the entry point to the webapp, that is `dist/app_bundle.js`. This js file is the one that is linked in the <head> section of `dist/index.html`, the html file used in production. 

I've two questions:
1) where shall I insert the changes I made to the` igv.js` library?
2) in `node-modules/igv-widgets/dist/igv-widgets.js` I added `"cstex"` in variable `knownFileExtensions` (I know I shall then create a new instance of the `igvteam/igv-widgets` repo with my changes in it).
Beside this change and linking my modified igv.js library, shall I edit other files/functions to be able to read cstex files in the igv webapp?

Sorry if this post is not an issue actually, but I did not know wherever else I could ask for support.
Thank you in advance for your help!

**Comment by jrobinso** [comment]
Your questions are really about how to do modern web development, not about our app per se.  There are a lot of resources available about this I can give a tutorial about node.js,  however in this case it is pretty simple as we don't use igv.js as an es6 module, it is just a script include in the page.    Just build your modified igv.js from the igv.js project (npm run build)  then link to that modified igv.js in the igv-webapp page, rather than our distribution.   You should never have to look or even know about the existence of "node_modules" or any depdent libraries, the build process takes care of all of that for you.
