### ISSUE TITLE
load from amazon s3 failed

### ISSUE THREAD

**Issue by girdhar3** [igvteam/igv-webapp#196]
I am trying to load a bedpe format file from amazon s3 bucket. the file has public permission. Unfortunately it is not working. and I see no error. I am able to load the file from local desktop but that disables the sharing of IGV web link.

https://igv.org/app/

Could you please help me with what could be the possible sources for no upload?

**Comment by jrobinso** [comment]
You probably need to add CORS support to your buckets.    See https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements#cross-origin-resource-sharing-cors

**Comment by jrobinso** [comment]
BTW Dropbox works with no configuration required.

**Comment by girdhar3** [comment]
Thanks. it works with dropbox :)

**Comment by jrobinso** [comment]
One caution about dropbox, if you remove any file you reference it the share links will be broken.   This seems obvious, but even if you replace the file with the exact name in the exact folder the share links will still be broken.   That's because the actual link to the file is a unique hash, the filename itself isn't really used.    This is how dropbox URLs work.   S3 urls do not have this problem, but they do require CORS setup.
