### ISSUE TITLE
plugin support

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv-webapp#58]
Hi Jim et al.

What are your thoughts about plugin support? I was looking at JBrowse the other day and saw some enormously interesting plugins (mygene/myvariant.info API support? Automated CSQ parsing? Sign me up!)

I would be great if some of those could be incorporated/ported to IGV.js or the webapp. I like jbrowse for the functionality, but the UI needs a lot of work, which IGV already has figured out. 

Thanks
M

**Comment by jrobinso** [comment]
There will not be a general plugin capability anytime soon.    However, tracks are highly configurable, although some work needs done on documenting how.    Actually that is a plugin  support or close to it.   For specific features such as the ones you mentioned open a separate issue for each one.   Adding support for mygene/myvariant should be very simple, but describe what you would want to do with those resources.    I don't know what CSQ parsing is so that will need more dsecription.

**Comment by matthdsm** [comment]
Hi Jim,

Thanks, I'll open different issues as needed!

Cheers
M
