### ISSUE TITLE
Loading local bigwig files during initiation

### ISSUE THREAD

**Issue by muriskar** [igvteam/igv-webapp#93]
I followed the instructions to install and run the IGV webapp. It works like a charm. 
I can load bigwig files using the GUI without problem. 
I don't have any experience in Javascript. 
I just want to initiate the IGV webapp together with the local bigwig files. I tried to modify genomes.json, "tracks": [ ... ] without success. What would be the easiest approach to load specific local files as made available from igv-webapp/dist/resources/? Which file should I need to modify? An example would be appreciated. Thanks a lot for your efforts.

"tracks": [
{
      	"type": "wig",
        "name": "H3K4me1",
        "format": "bigwig",
        "filename": "example_data_hg19.bw",
        "url": "resources/localdatafolder/example_data_hg19.bw",
        "sourceType": "file",
        "color": "rgb(150,150,150)",
        "autoscale": true,
        "height": 50,
        "order": 2
      }
]

**Comment by helgathorv** [comment]
Due to browser-imposed security restrictions, you cannot automatically load a local file.

**Comment by muriskar** [comment]
Thanks. What would the best way to load bigwig files from URLs during initiation? Because the file will be available from the webserver. I think they should be CORS-enabled as far as I read.

**Comment by jrobinso** [comment]
@muriskar Don't add the filename attribute, otherwise,  assuming "resources" is a folder under your web server route.  If its not working what are the symptoms, and can you post the entire web page or at least the "<script> ...  </script> section that initiates igv.

Your question is really about configuring igv.js,  documentation is here:  https://github.com/igvteam/igv.js/wiki/Tracks-2.0.   Pull from the igv.js repository, there is an examples folder with lots of examples.

**Comment by muriskar** [comment]
Resources is a folder under the web server root. Thanks a lot for directing me. Yes, it took me some time to realize that I need to update the igvConfig:{} within igvwebConfig.js. It works great now. Thanks again for the tool.
