### ISSUE TITLE
Cannot load bam from URL

### ISSUE THREAD

**Issue by mchaisso** [igvteam/igv-webapp#98]
Hi, I'm trying to load a bam (+index). When I point my browser to the URL, it downloads the bam, so it is accessible.  There is an error loading track data. If I download locally the data will display.

A link to the session is here:  http://bit.ly/2MQaFiD

**Comment by jrobinso** [comment]
Hi @mchaisso ,  what do you mean by  "when I point my browser to the URL"?  Also, what downloads the bam?   I'm not really able to understand the issue.   Please tell us exactly what you are doing, step by step.

**Comment by mchaisso** [comment]
Hi Jim, sorry for the ambiguity. When I paste the URL to the bam into my browser, it downloads the bam (same with the .bai). In web IGV, I go to tracks->URL, and enter the same URL for the bam&bai, then click "ok". I then zoom in until it is small enough resolution to view the data, and ITV-web displays "Error loading track data".

**Comment by jrobinso** [comment]
If the bam is public could you share the URL here?  If its not look in the
javascript console and note any errors.   Also,  use the "network" tab in
developer tools to see errors.    Since you can download from the browser
the problem is likely either  (1) the server the BAM file is on does not
support CORS,  or (2) the server the BAM file is on does not support
"Range" requests.   See the data server requirements in the wiki
documentation for more details,  or google  "CORS javascript".

**Comment by mchaisso** [comment]
Sure, here you go:
http://www-rcf.usc.edu/~mchaisso/bams/ERR2631600.fastq.bam
http://www-rcf.usc.edu/~mchaisso/bams/ERR2631600.fastq.bam.bai

**Comment by mchaisso** [comment]
Ah, I checked the console - it needs to be through https.  I'll contact the
administrators here.

Thanks!
-Mark

**Comment by jrobinso** [comment]
The https problem can be gotten around by using http://igv.org/app.
 However that's not the main problem, the server doesn't support CORS
requests so it can be accessed from any javascript problem.    See
https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements.   Google
for "CORS Javascript" for more info.
